config/routes.rb
Rails.application.routes.draw do
  resources :hacks
  resources :users
  resources :usrs
  resources :resps
  resources :posts
  resources :tests

  root 'application#index'

  
  

end

app/models/hack.rb
class Hack < ActiveRecord::Base
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
  before_action :set_hack, only: [:show, :edit, :update, :destroy]

  # GET /hacks
  # GET /hacks.json
  def index
    @hacks = Hack.all
  end

  # GET /hacks/1
  # GET /hacks/1.json
  def show
  end

  # GET /hacks/new
  def new
    @hack = Hack.new
  end

  # GET /hacks/1/edit
  def edit
  end

  # POST /hacks
  # POST /hacks.json
  def create
    @hack = Hack.new(hack_params)

    respond_to do |format|
      if @hack.save
        format.html { redirect_to @hack, notice: 'Hack was successfully created.' }
        format.json { render :show, status: :created, location: @hack }
      else
        format.html { render :new }
        format.json { render json: @hack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hacks/1
  # PATCH/PUT /hacks/1.json
  def update
    respond_to do |format|
      if @hack.update(hack_params)
        format.html { redirect_to @hack, notice: 'Hack was successfully updated.' }
        format.json { render :show, status: :ok, location: @hack }
      else
        format.html { render :edit }
        format.json { render json: @hack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hacks/1
  # DELETE /hacks/1.json
  def destroy
    @hack.destroy
    respond_to do |format|
      format.html { redirect_to hacks_url, notice: 'Hack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hack
      @hack = Hack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hack_params
      params.require(:hack).permit(:mac, :name, :heartbeat, :self_latitude, :self_longitude, :sanc_latitude, :sanc_longitude, :direction, :distance)
    end
end

app/helpers/hacks_helper.rb
module HacksHelper
end

app/views/hacks/_form.html.erb
<%= form_for(@hack) do |f| %>
  <% if @hack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hack.errors.count, "error") %> prohibited this hack from being saved:</h2>

      <ul>
      <% @hack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mac %><br>
    <%= f.text_field :mac %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :heartbeat %><br>
    <%= f.number_field :heartbeat %>
  </div>
  <div class="field">
    <%= f.label :self_latitude %><br>
    <%= f.text_field :self_latitude %>
  </div>
  <div class="field">
    <%= f.label :self_longitude %><br>
    <%= f.text_field :self_longitude %>
  </div>
  <div class="field">
    <%= f.label :sanc_latitude %><br>
    <%= f.text_field :sanc_latitude %>
  </div>
  <div class="field">
    <%= f.label :sanc_longitude %><br>
    <%= f.text_field :sanc_longitude %>
  </div>
  <div class="field">
    <%= f.label :direction %><br>
    <%= f.number_field :direction %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hacks/edit.html.erb
<h1>Editing Hack</h1>

<%= render 'form' %>

<%= link_to 'Show', @hack %> |
<%= link_to 'Back', hacks_path %>

app/views/hacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hacks</h1>

<table>
  <thead>
    <tr>
      <th>Mac</th>
      <th>Name</th>
      <th>Heartbeat</th>
      <th>Self latitude</th>
      <th>Self longitude</th>
      <th>Sanc latitude</th>
      <th>Sanc longitude</th>
      <th>Direction</th>
      <th>Distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hacks.each do |hack| %>
      <tr>
        <td><%= hack.mac %></td>
        <td><%= hack.name %></td>
        <td><%= hack.heartbeat %></td>
        <td><%= hack.self_latitude %></td>
        <td><%= hack.self_longitude %></td>
        <td><%= hack.sanc_latitude %></td>
        <td><%= hack.sanc_longitude %></td>
        <td><%= hack.direction %></td>
        <td><%= hack.distance %></td>
        <td><%= link_to 'Show', hack %></td>
        <td><%= link_to 'Edit', edit_hack_path(hack) %></td>
        <td><%= link_to 'Destroy', hack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hack', new_hack_path %>

app/views/hacks/new.html.erb
<%= javascript_include_tag "application" %>
<h1>New Hack</h1>
<% if true %>
<% p = @hack %>
<% p.mac        = params[:mac]%>
<% p.name       = params[:name]%>
<% p.heartbeat = params[:heartbeat] %>
<% p.self_latitude  = params[:self_latitude]   %>
<% p.self_longitude = params[:self_longitude] %>


<% p.sanc_latitude  = 25.019246 %>
<% p.sanc_longitude = 121.542264 %>

<% self_la = p.self_latitude.to_f  %>
<% self_lo = p.self_longitude.to_f %>
<% sanc_la = p.sanc_latitude.to_f  %>
<% sanc_lo = p.sanc_longitude.to_f %>

<% p.distance = Math.sqrt(((sanc_la - self_la) * 111267.47*(sanc_la - self_la) * 111267.47 + (sanc_lo - self_lo) * 110892.76*(sanc_lo - self_lo) * 110892.76)).to_i %>

<% arc  = (Math.atan2((sanc_la - self_la), (sanc_lo - self_lo)))*57.32484 %>
<% p.direction = -(arc - 90) %>


<% if !p.name.nil? %>
  <% p.save! %>
<% end %>
<% end %>

app/views/hacks/show.html.erb
<% mac = params[:mac] %>

<% Hack.all.distinct.reverse.each do |u| %>
  <% if (mac == u.mac) %>
    <% if (params[:latitude] == "1") %>
        <%= u.sanc_latitude %>
        <% break %>
    <% else %>
      <%= u.sanc_longitude %>   
      <% break %>
    <% end %> 
  <% end %>
<% end %>