config/routes.rb
Rails.application.routes.draw do
  resources :hacks
  resources :users
  resources :usrs
  resources :resps
  resources :posts
  resources :tests

  root 'application#index'

  
  

end

app/models/usr.rb
class Usr < ActiveRecord::Base
end

app/controllers/usrs_controller.rb
class UsrsController < ApplicationController
  before_action :set_usr, only: [:show, :edit, :update, :destroy]

  # GET /usrs
  # GET /usrs.json
  def index
    @usrs = Usr.all
  end

  # GET /usrs/1
  # GET /usrs/1.json
  def show
    respond_to do |format|
      format.html 
      format.json { render :text => "Fuck!"}
    end
  end

  # GET /usrs/new
  def new
    @usr = Usr.new
  end

  # GET /usrs/1/edit
  def edit
  end

  # POST /usrs
  # POST /usrs.json
  def create
    @usr = Usr.new(usr_params)

    respond_to do |format|
      if @usr.save
        format.html { redirect_to @usr, notice: 'Usr was successfully created.' }
        format.json { render :show, status: :created, location: @usr }
      else
        format.html { render :new }
        format.json { render json: @usr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usrs/1
  # PATCH/PUT /usrs/1.json
  def update
    respond_to do |format|
      if @usr.update(usr_params)
        format.html { redirect_to @usr, notice: 'Usr was successfully updated.' }
        format.json { render :show, status: :ok, location: @usr }
      else
        format.html { render :edit }
        format.json { render json: @usr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usrs/1
  # DELETE /usrs/1.json
  def destroy
    @usr.destroy
    respond_to do |format|
      format.html { redirect_to usrs_url, notice: 'Usr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usr
      @usr = Usr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usr_params
      params.require(:usr).permit(:mac, :name, :heart_beat, :self_latitude, :self_longitude, :sanc_latitude, :sanc_longitude, :direction)
    end
end

app/helpers/usrs_helper.rb
module UsrsHelper
end

app/views/usrs/_form.html.erb
<%= javascript_include_tag "application" %>
<% if true %>
<% p = @usr %>
<% p.mac        = params[:mac]%>
<% p.name       = params[:name]%>
<% p.heart_beat = params[:heart_beat] %>
<% p.self_latitude   = params[:self_latitude]   %>
<% p.self_longitude = params[:sanc_longitude] %>
<% p.sanc_latitude   = params[:self_latitude]   %>
<% p.sanc_longitude = params[:sanc_longitude] %>
<% p.direction  = params[:direction] %>
<% if !p.name.nil? %>
  <% p.save! %>
<% end %>
<% end %>

app/views/usrs/edit.html.erb
<h1>Editing Usr</h1>

<%= render 'form' %>

<%= link_to 'Show', @usr %> |
<%= link_to 'Back', usrs_path %>

app/views/usrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usrs</h1>

<table>
  <thead>
    <tr>
      <th>Mac </th>
      <th>Name </th>
      <th>Heart beat </th>
      <th>Self latitude </th>
      <th>Self longitude </th>
      <th>Sanc latitude </th>
      <th>Sanc longitude </th>
      <th>Direction </th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usrs.each do |usr| %>
      <tr>
        <td><%= usr.mac %></td>
        <td><%= usr.name %></td>
        <td><%= usr.heart_beat %></td>
        <td><%= usr.self_latitude %></td>
        <td><%= usr.self_longitude %></td>
        <td><%= usr.sanc_latitude %></td>
        <td><%= usr.sanc_longitude %></td>
        <td><%= usr.direction %></td>
        <td><%= link_to 'Show', usr %></td>
        <td><%= link_to 'Edit', edit_usr_path(usr) %></td>
        <td><%= link_to 'Destroy', usr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usr', new_usr_path %>

app/views/usrs/new.html.erb
<h1>New Usr</h1>

<%= render 'form' %>

<%= link_to 'Back', usrs_path %>

app/views/usrs/show.html.erb
Mac:
  <%= @usr.mac %>
Name:
  <%= @usr.name %>
Heart beat:
  <%= @usr.heart_beat %>
Self latitude:
  <%= @usr.self_latitude %>
Self longitude:
  <%= @usr.self_longitude %>
Sanc latitude:
  <%= @usr.sanc_latitude %>
Sanc longitude:
  <%= @usr.sanc_longitude %>
T.integer:
  <%= @usr.t.integer %>